// Random game data that is added to Firestore
// After you've signed into Game Reviews, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  gameNames: [
    "Cyber Legends",
    "Dragon Quest Chronicles",
    "Space Warriors",
    "Mystic Realms",
    "Battle Arena",
    "Racing Thunder",
    "Adventure Quest",
    "Puzzle Master",
    "Sports Champion",
    "Fantasy Kingdom",
    "Stealth Mission",
    "Racing Legends",
    "Combat Zone",
    "Magic Academy",
    "Space Explorer",
    "Racing Fury",
    "Adventure Hero",
    "Puzzle Quest",
    "Sports Pro",
    "Fantasy World",
    "Stealth Assassin",
    "Racing Storm",
    "Combat Master",
    "Magic Tower",
    "Space Odyssey",
    "Racing Champion",
    "Adventure Tales",
    "Puzzle Galaxy",
    "Sports League",
    "Fantasy Quest",
    "Stealth Ninja",
    "Racing Speed",
    "Combat Arena",
    "Magic Forest",
    "Space Colony",
    "Racing Thunder",
    "Adventure Land",
    "Puzzle Master",
    "Sports Victory",
    "Fantasy Realm",
    "Stealth Agent",
    "Racing Legends",
    "Combat Force",
    "Magic Castle",
    "Space Station",
    "Racing Fury",
    "Adventure Quest",
    "Puzzle Galaxy",
    "Sports Champion",
    "Fantasy Kingdom",
  ],
  gamePlatforms: [
    "PC",
    "PlayStation",
    "Xbox",
    "Nintendo Switch",
    "Mobile",
    "Steam Deck",
    "PlayStation VR",
    "Meta Quest",
    "iOS",
    "Android",
    "Mac",
  ],
  gameGenres: [
    "Action",
    "RPG",
    "Strategy",
    "Sports",
    "Adventure",
  ],
  gameReviews: [
    { text: "Absolutely incredible game! The gameplay is phenomenal!", rating: 5 },
    { text: "Amazing graphics and engaging story. Highly recommended!", rating: 5 },
    { text: "The mechanics are so smooth and satisfying.", rating: 5 },
    { text: "Great multiplayer experience and friendly community.", rating: 5 },
    { text: "A masterpiece of game design!", rating: 5 },
    {
      text: "Addictive gameplay that kept me hooked for hours.",
      rating: 5,
    },
    { text: "Perfect balance of challenge and fun.", rating: 5 },
    { text: "Incredible attention to detail and polish.", rating: 5 },
    { text: "Good game with solid mechanics.", rating: 4 },
    { text: "Enjoyed playing this, would recommend.", rating: 4 },
    { text: "Decent gameplay and reasonable price.", rating: 4 },
    { text: "Fun game, but some bugs need fixing.", rating: 3 },
    { text: "Decent experience, but nothing extraordinary.", rating: 3 },
    { text: "The gameplay was average, could be better.", rating: 3 },
    {
      text: "Loading times were slow, and the gameplay was disappointing.",
      rating: 2,
    },
    { text: "Expected more, but left unsatisfied.", rating: 2 },
    { text: "Underwhelming graphics and repetitive gameplay.", rating: 2 },
    { text: "Disappointing experience overall.", rating: 2 },
    {
      text: "The game was terrible, will never play again.",
      rating: 1,
    },
    {
      text: "Worst gaming experience I've had so far.",
      rating: 1,
    },
    { text: "Avoid this game, it's completely broken.", rating: 1 },
    { text: "Unplayable due to bugs and poor optimization.", rating: 1 },
    { text: "Simply outstanding! A gaming masterpiece.", rating: 5 },
    { text: "Couldn't stop playing, absolutely addictive.", rating: 5 },
    { text: "Top-notch quality, worth every penny.", rating: 5 },
    { text: "Highly recommended for gaming enthusiasts.", rating: 5 },
    { text: "Exquisite gameplay that pleased my gaming needs.", rating: 5 },
    { text: "A gem of a game, impeccable in every aspect.", rating: 5 },
    { text: "Excellent variety of content and replayability.", rating: 5 },
    { text: "A fantastic gaming experience overall.", rating: 5 },
    {
      text: "The atmosphere was immersive, perfect for long sessions.",
      rating: 4,
    },
    { text: "Good gameplay, but the UI could be improved.", rating: 4 },
    {
      text: "Pleasantly surprised by the depth of content.",
      rating: 4,
    },
    { text: "Well-designed levels and engaging progression.", rating: 4 },
    { text: "Satisfying gameplay, suitable for casual gaming.", rating: 4 },
    { text: "The gameplay was okay, nothing special.", rating: 3 },
    {
      text: "Controls could be better, but the gameplay was fine.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more value for the price.", rating: 2 },
    { text: "Mediocre graphics and lackluster gameplay.", rating: 2 },
    {
      text: "Regret spending money on such a disappointing game.",
      rating: 2,
    },
    { text: "Not up to par with my expectations.", rating: 2 },
  ],
};
